apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service:latest
          ports:
            - containerPort: 8095
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server:8100/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP
