apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
        - name: practitioner-service
          image: practitioner-service:latest
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          environment:
            - name: EUREKA_SERVER
              value: http://eureka-server:8100/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: practitioner-service-service
spec:
  selector:
    app: practitioner-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
